import { buildLanguageDirective } from "@/lib/output-language"

export const PROMPTS = {
  chapterGeneration: (contextPack: string, chapterGoal: string) =>
    [
      contextPack,
      "",
      "请根据以上上下文包和大纲，撰写以下章节：",
      chapterGoal,
      "",
      "要求：",
      "1. 严格遵循大纲中的情节走向",
      "2. 保持人物性格和说话方式一致",
      "3. 不要泄露角色尚不知道的信息",
      "4. 注意伏笔的埋设和回收",
      "5. 章节结尾要有钩子，吸引读者继续阅读",
      "6. 字数控制在 3000-5000 字",
    ].join("\n"),

  chapterContinuation: (contextPack: string, lastParagraph: string) =>
    [
      contextPack,
      "",
      "上一段内容：",
      lastParagraph,
      "",
      "请续写以下内容，保持风格和节奏一致：",
    ].join("\n"),

  chapterRevision: (contextPack: string, originalContent: string, revisionNotes: string) =>
    [
      contextPack,
      "",
      "原始章节内容：",
      originalContent.slice(0, 6000),
      "",
      "修改要求：",
      revisionNotes,
      "",
      "请根据修改要求重写章节，保持其他部分不变：",
    ].join("\n"),

  outlineGeneration: (genre: string, scale: string, premise: string, context = "") =>
    [
      `请为以下小说生成大纲：`,
      "",
      `类型：${genre}`,
      `规模：${scale}`,
      `核心设定：${premise}`,
      "",
      "已有故事记忆与项目资料（如果有）：",
      context || "暂无可用的剧情记忆、卡片故事或设定，请基于本次大纲提示词先生成初始版大纲。",
      "",
      buildLanguageDirective(premise),
      "",
      "请输出以下内容：",
      "1. 总大纲（包含起承转合、主要冲突线、情感线）",
      "2. 分卷大纲（根据规模合理分卷，每卷10-20章，标注每卷核心事件和转折点）",
      "3. 主要人物设定（姓名、性格、动机、人物弧线、关键关系）",
      "4. 世界观设定（核心设定规则、势力分布、能力体系、重要地点）",
      "5. 伏笔计划（主要伏笔的埋设、推进、回收节点）",
    ].join("\n"),

  outlineRefinementGeneration: (outlineContext: string, sectionHints: string, userRequest: string) =>
    [
      "请基于已有大纲和项目记忆，对小说进行一次统一的细化生成。",
      "",
      "硬性约束：",
      "1. 已有大纲、人物状态、角色认知、伏笔状态、时间线、正史规则和项目记忆都是最高优先级，不得推翻。",
      "2. 本次用户要求只能用于补充、聚焦和完善，不得改写既定主线和核心设定。",
      "3. 如果信息不足，只能做最小必要补完，且必须与现有设定兼容。",
      "",
      "已有大纲与项目记忆：",
      outlineContext,
      "",
      "本次细化重点：",
      userRequest.trim() || "未额外指定，请基于已有大纲与项目记忆完成全量细化。",
      "",
      buildLanguageDirective(userRequest || outlineContext),
      "",
      "请一次性覆盖以下 6 类细化内容：",
      sectionHints,
      "",
      "输出要求：",
      "1. 只返回一个 JSON 对象，不要输出解释、前言、额外说明或代码块外文本。",
      "2. JSON 必须包含以下 6 个字段，且每个字段的值都必须是字符串形式的中文 Markdown：",
      '   - "chapterOutlines"',
      '   - "characterBriefs"',
      '   - "organizationsOutline"',
      '   - "powerSystem"',
      '   - "foreshadowingPlan"',
      '   - "locationsOutline"',
      "3. chapterOutlines 必须体现章节目标、冲突、转折和结尾钩子。",
      "4. characterBriefs 必须覆盖人物动机、弧线、关系和当前状态。",
      "5. organizationsOutline、powerSystem、locationsOutline 必须写清规则、限制、代价、归属与剧情作用。",
      "6. foreshadowingPlan 必须体现伏笔的埋设、推进、回收节点和对应章节。",
    ].join("\n"),

  consistencyCheck: (contextPack: string, chapterContent: string) =>
    [
      contextPack,
      "",
      "请检查以下章节的连贯性：",
      chapterContent.slice(0, 8000),
      "",
      "检查维度：",
      "1. 人设一致性",
      "2. 时间线准确性",
      "3. 伏笔状态",
      "4. 角色认知合理性",
      "5. 设定一致性",
    ].join("\n"),

  inspirationCoachSystem: (chapterMemory: string, outlineContext: string) =>
    [
      "你是长篇小说的剧情策划教练。你的任务不是替作者写正文，也不是一上来替作者定细节，而是通过**由粗到细的剧情发展引导**先帮助作者确定大方向，再逐步收窄到可用的续写灵感。",
      "",
      "工作方式：",
      "1. 第一轮只给 3-5 个粗略大方向，不写具体事件链。每个方向控制在 1-2 句话，只说明故事会往哪类局面走。",
      "2. 作者选定、混合或修正方向后，第二轮再把方向收窄到 2-3 个中等颗粒度的推进方案；每个方案只写核心变化，不展开章节细节。",
      "3. 只有作者明确表示要细化、生成、继续深入时，才进入细化阶段，给出较具体的事件顺序。",
      "4. 每轮都先承接作者上一轮选择，再给下一层内容；如果作者没选，就继续停留在粗方向层，不要擅自细化。",
      "5. 按以下层级推进：",
      "   ① 粗方向：例如关系线转向、外部危机转向、身份/秘密转向、势力冲突转向、情绪基调转向。",
      "   ② 中方案：说明这条方向会让主角、关键人物、局势或线索发生什么总体变化。",
      "   ③ 细事件：在作者确认后，再列少量按时间推进的事件节点。",
      "6. 综合产出阶段只写「后续会发生什么事件」和「时间线顺序」，像事件清单而非细纲；不要展开每章目标/冲突/伏笔/钩子，不要写正文。",
      "",
      "硬性约束：",
      "1. 选中章节记忆是最高优先级，不得推翻其中的人物状态、认知边界、时间线和已发生事件。",
      "2. 可以提出新冲突、新误会、新选择和新线索，但必须说明它们如何从已发生剧情自然生长出来。",
      "3. 不写正文，不输出 JSON，不输出代码块，只输出 Markdown。",
      "4. 不要使用分析标签或术语，不要把选项写成点评、优劣比较或创作课笔记。",
      "5. 第一轮禁止出现具体章节号、连续事件链、详细人物行动、具体对白或完整场景设定。",
      "6. 不要用提问作为主要输出形式；允许在末尾用一句很短的话邀请作者选择、混合或修正方向。",
      "7. 每轮回复尽量简短（第一轮一般不超过 220 字，后续一般不超过 350 字），把创作决定权交给作者。",
      "",
      buildLanguageDirective(chapterMemory || outlineContext),
      "",
      outlineContext.trim()
        ? `已选参考内容：\n${outlineContext.trim()}`
        : "当前未选择额外参考内容。",
      "",
      "选中章节记忆：",
      chapterMemory.trim() || "未提供选中章节记忆，请主要依据作者本轮回答进行引导。",
    ].join("\n"),

  inspirationSynthesizeUser: () =>
    [
      "请基于以上几轮对话，综合产出后续剧情的续写灵感。",
      "",
      "重要：输出要克制、像事件清单，而不是细纲。只写「后续会发生什么事件」和「时间线顺序」，不要展开每章的目标/冲突/伏笔/钩子等细节，不要写正文。",
      "",
      "输出结构（只用 Markdown，不要 JSON/代码块）：",
      "## 后续时间线与事件",
      "- 按时间先后列出后续 6-10 个关键事件节点，每条一句话简述发生了什么，并在句末用括号标注大致章节区间或时间位置，例如：（第25-28章）。",
      "- 事件之间要体现因果与推进关系，不要写成流水账，也不要每条展开多句。",
      "",
      "## 可选走向（可选）",
      "- 最多 2-3 条不同走向，每条一句话点明差异即可，不展开。",
      "",
      "## 风险提醒（可选）",
      "- 最多 2-3 条最容易写崩的认知/时间线风险，每条一句话。",
    ].join("\n"),
} as const
