import { CHAPTER_BODY_EXCERPT_MAX_CHARS } from "./chapter-excerpts"
import { buildLanguageDirective } from "@/lib/output-language"

export const PROMPTS = {
  chapterGeneration: (contextPack: string, chapterGoal: string) =>
    [
      contextPack,
      "",
      "请根据以上上下文包和大纲，撰写以下章节：",
      chapterGoal,
      "",
      "要求：",
      "1. 严格遵循大纲中的情节走向",
      "2. 保持人物性格和说话方式一致",
      "3. 不要泄露角色尚不知道的信息",
      "4. 注意伏笔的埋设和回收",
      "5. 章节结尾要有钩子，吸引读者继续阅读",
      "6. 字数控制在 3000-5000 字",
    ].join("\n"),

  chapterContinuation: (contextPack: string, lastParagraph: string) =>
    [
      contextPack,
      "",
      "上一段内容：",
      lastParagraph,
      "",
      "请续写以下内容，保持风格和节奏一致：",
    ].join("\n"),

  chapterRevision: (contextPack: string, originalContent: string, revisionNotes: string) =>
    [
      contextPack,
      "",
      "原始章节内容：",
      originalContent.slice(0, 6000),
      "",
      "修改要求：",
      revisionNotes,
      "",
      "请根据修改要求重写章节，保持其他部分不变：",
    ].join("\n"),

  consistencyCheck: (contextPack: string, chapterContent: string) =>
    [
      contextPack,
      "",
      "请检查以下章节的连贯性：",
      chapterContent.slice(0, CHAPTER_BODY_EXCERPT_MAX_CHARS),
      "",
      "检查维度：",
      "1. 人设一致性",
      "2. 时间线准确性",
      "3. 伏笔状态",
      "4. 角色认知合理性",
      "5. 设定一致性",
    ].join("\n"),

  OUTLINE_METHODOLOGY_VOLUME: [
    "## 卷纲方法论",
    "",
    "### 八节点结构",
    "每卷必须标注以下四个关键节点：",
    "- 1/4 节点：第一个重要转折",
    "- 中点：本卷中点关键事件",
    "- 3/4 节点：推进至最终高潮的关键转折",
    "- 高潮节点：本卷最高潮",
    "",
    "### 章节定位分类",
    "每章需标注定位标签：开场 / 发展 / 铺垫 / 转折 / 高潮 / 收束",
    "",
    "### 情绪弧线设计原则",
    "采用W形折线：起点→下降→回升→再降→最终回升",
    "",
    "### 爽点节律公式",
    "每章需标注章节区间、爽点类型、具体内容和预期效果",
  ].join("\n"),

  OUTLINE_METHODOLOGY_CHAPTER: [
    "## 细纲方法论",
    "",
    "### 五段式结构",
    "每章细纲必须按五段组织：起因 → 发展 → 转折 → 高潮 → 结尾",
    "",
    "### 多线安排",
    "需标注主线推进、辅线推进、事件线/任务线、感情线/关系线、逻辑线",
    "",
    "### 情节点功能标签",
    "每个情节点需标注功能标签和代价/收益兑现",
    "",
    "### 情绪变化标注",
    "标注起点→终点情绪变化路径",
    "",
    "### 钩子类型",
    "章首钩子类型：悬念对话开局 / 闪前碎片 / 倒计时开局 / 神秘独白 / 反差场景 / 未完成动作开局 / 意象预示",
    "章尾钩子类型：突然揭示 / 紧急危机 / 未完成动作 / 身份反转 / 两难抉择 / 神秘物品/线索 / 倒计时 / 承诺/威胁 / 离奇消失 / 隐藏含义 / 意象钩子 / 回声钩子 / 留白钩子",
  ].join("\n"),

  TRACKING_AWARENESS: [
    "## 伏笔与状态追踪要求",
    "",
    "1. 伏笔管理：明确标注伏笔的埋设、推进和回收节点，避免伏笔悬空",
    "2. 角色状态变化：角色能力、认知、关系、位置的变化必须可追踪，前后一致",
    "3. 信息差管理：不同角色之间的信息差必须明确标注，并控制信息释放节奏",
  ].join("\n"),

  WRITING_STYLE_TEMPLATE: [
    "## 文风设定",
    "",
    "以下为作品的文风偏好设定，请在撰写时严格遵循：",
    "",
    "### 句式偏好",
    "{sentencePreference}",
    "",
    "### 用词习惯",
    "{wordHabits}",
    "",
    "### 对话风格",
    "{dialogueStyle}",
    "",
    "### 节奏特点",
    "{rhythmFeatures}",
    "",
    "### 禁忌表达",
    "{tabooExpressions}",
  ].join("\n"),

  inspirationCoachSystem: (chapterMemory: string, outlineContext: string) =>
    [
      "你是长篇小说的剧情策划教练。请通过由粗到细的剧情发展引导，先帮助作者确定大方向，再逐步收窄到可用的续写灵感。",
      "",
      "工作方式：",
      "1. 第一轮只给 3-5 个粗略大方向，每个方向控制在 1-2 句话，不写具体事件链。",
      "2. 作者选定、混合或修正方向后，再给 2-3 个中等颗粒度的推进方案。",
      "3. 只有作者明确要求继续细化时，才给出较具体的事件顺序。",
      "4. 每轮先承接作者上一轮选择，再提供下一层内容。",
      "5. 综合产出只写后续事件和时间线顺序，不写正文，也不展开为逐章细纲。",
      "",
      "硬性约束：",
      "1. 选中章节记忆是最高优先级，不得推翻人物状态、认知边界、时间线和已发生事件。",
      "2. 新冲突、新误会、新选择和新线索必须从已发生剧情自然生长出来。",
      "3. 不输出 JSON 或代码块，只输出 Markdown。",
      "4. 不要用提问作为主要输出形式。",
      "5. 第一轮禁止出现具体章节号、连续事件链、具体对白或完整场景设定。",
      "",
      buildLanguageDirective(chapterMemory || outlineContext),
      "",
      outlineContext.trim()
        ? `已选参考内容：\n${outlineContext.trim()}`
        : "当前未选择额外参考内容。",
      "",
      "选中章节记忆：",
      chapterMemory.trim() || "未提供选中章节记忆，请主要依据作者本轮回答进行引导。",
    ].join("\n"),

  inspirationSynthesizeUser: () =>
    [
      "请基于以上几轮对话，综合产出后续剧情的续写灵感。",
      "",
      "只写后续会发生什么事件和时间线顺序，不要展开每章目标、冲突、伏笔或钩子，不要写正文。",
      "",
      "## 后续时间线与事件",
      "- 按时间先后列出 6-10 个关键事件节点，每条一句话，并标注大致章节区间或时间位置。",
      "- 事件之间要体现因果与推进关系。",
      "",
      "## 可选走向（可选）",
      "- 最多 2-3 条，每条一句话点明差异。",
      "",
      "## 风险提醒（可选）",
      "- 最多 2-3 条最容易写崩的认知或时间线风险。",
    ].join("\n"),
} as const
